language: generic 
sudo: required
services:
  - docker

before_intall:
  - docker build -t jbdockerdev/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true jbdockerdev/docker-react npm run test
